### ISSUE TITLE
Please provide facility for configuring the Rust compiler version

### ISSUE THREAD

**Issue by Betterbird** [4ch1m/ansible-betterbird#3]
When setting up the build for the first time, it installs the latest version of the Rust compiler during `mach bootstrap`. Currently that is version 1.58.1 of January 2022, but to compile the "older" Mozilla source version 1.53.0 of June 2021 is needed.

Fortunately Rust allows easy version switching, so after installation this command activates the correct version:
`rustup override set 1.53.0`

Theoretically it's possible that other compiler versions need to be "pinned", like for example clang, but so far, the Rust compiler is the only one that has come up. The issue is that the more modern Rust compiler refuses to compile some of the older code.

**Comment by 4ch1m** [comment]
done; see 4a710ab54bdd5fc23e08d9b2e2d23f6c4c33e761
