### ISSUE TITLE
Provide a way to compile two BB versions

### ISSUE THREAD

**Issue by Betterbird** [4ch1m/ansible-betterbird#4]
Betterbird major versions always overlap for a few months. BB 102 comes out at the end of June, the beta even earlier, and BB 91 will be supported until the end of August 2022 or longer. So something like `./betterbird.sh NN` with NN being the version would be useful.

That's also related to issue #3 where different BB versions may need different compiler versions.

**Comment by 4ch1m** [comment]
We can add more "extra config" tasks to [extra_config.yml](https://github.com/4ch1m/ansible-betterbird/blob/master/tasks/extra_config.yml); which can easily be triggered by adding (or removing) a specific line in the according vars-file.

Please provide some more concrete examples/use-cases.

**Comment by Betterbird** [comment]
Hmm, did you read the initial comment?

`./betterbird.sh` builds the release given in 
https://github.com/Betterbird/thunderbird-patches/blob/aa8ea10b7032450ca420858e1969a017a6c753c1/releases.yml#L12

However, there are times when there can be two "current" releases.

**Comment by 4ch1m** [comment]
> Hmm, did you read the initial comment?

Yes, I did.
Did you have a look at 4a710ab54bdd5fc23e08d9b2e2d23f6c4c33e761?

> `./betterbird.sh` builds the release given in https://github.com/Betterbird/thunderbird-patches/blob/aa8ea10b7032450ca420858e1969a017a6c753c1/releases.yml#L12

I'm aware of that.
I came up with this concept in first place. Remember?

With the latest release of this repo **you** can control/pin the Rust-compiler version (which fits to your release-version) by simply putting `rustup_override: 1.53.0` inside your `release.yml`.

These overrides can be set on three places (in this precedence):
1. release.yml
1. extra_config_vars.yml (on playbook-level; as documented)
1. as extra vars passed on the Ansible command-line

> However, there are times when there can be two "current" releases.

Building two current releases (in one (Ansible-)run) is overkill imho.

Well...

What I was trying to say
If there are more things that need overrides (other compiler versions, framework versions, etc.); then please provide examples, so you/we we can add them.

**Comment by Betterbird** [comment]
Thanks for the changes. We've not edited our `releases.yml` like so:
https://github.com/Betterbird/thunderbird-patches/blob/138aa0fe8cb325e7fc09b61ecbc4938df99c823c/releases.yml
As requested/advised via PM, `rustup_override: 1.53.0` is now release specific.

We'd still be interested to know how to trigger a build for `daily102`, which in due course will become `beta102` and then `esr102`. Also, the Ansible build pulls the Mozilla source into a `source` directory, it would be better to pull into the respective Mozilla directory. Otherwise this repos would have to be cloned twice to get two different source directories.

Thanks for the consideration.
